services:
  - type: web
    name: quest-supremacy-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.main_prod:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: quest-supremacy-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://quest-supremacy-irl.vercel.app,http://localhost:5173

databases:
  - name: quest-supremacy-db
    databaseName: quest_supremacy
    user: quest_user
